# Generated by Django 4.0 on 2022-03-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter task title', max_length=120)),
                ('description', models.TextField(help_text='Enter task description')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
